### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by Abhinav-3359**

### CODE REVIEW

**Comment by Abhinav-3359** [comment]
sir pls review

**Comment by akshat-singh-dev** [comment]
@Abhinav-3359 Avoid using any frameworks like bootstrap as this is a vanilla project.
Also make a simple centre aligned footer.

**Comment by Abhinav-3359** [comment]
Okay sir I’ll change

**Comment by akshat-singh-dev** [comment]
@SparshMc07 added footer

**Pull request closed without merging**
